# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js

on: [push, pull_request]

jobs:
  run:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    env:
        DB_DATABASE: test
        DB_USER: root
        DB_PASSWORD: root

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
        
    - name: Install adonis and 
      run: sudo npm i -g @adonisjs/cli
      
    - name: Install bodyparser
      run: adonis install @adonisjs/bodyparser
        
    - name: Install dependencies
      run: yarn

    - name: Prepare Adonis Application
      run: |
        cp .env.ci .env
        adonis key:generate
        cp .env .env.testing 
            
    - name: Run tests
      run: yarn test
