# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js

on: [push, pull_request]

jobs:
  run:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
            
    - name: Define env to node ace
      env: 
        APP_KEY: ${{ secrets.APP_KEY }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USER: ${{ secrets.DB_USER }}
        MAIL_HOST: ${{ secrets.MAIL_HOST }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        MAIL_PORT: ${{ secrets.MAIL_PORT }}
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        SESSION_DRIVER: ${{ secrets.SESSION_DRIVER }}
      run: node ace --env ${{ env }}
      
    - name: Secrets to env
      uses: shine1594/secrets-to-env-action@v1.5.2
      with:
        secrets: ${{ toJSON(secrets) }}
        secrets_env: all
            
    - name: Run tests
      run: yarn test
