# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js

on: [push, pull_request]

jobs:
  run:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
      
    - name: Secrets to env
      uses: shine1594/secrets-to-env-action@v1.5.2
      with:
        secrets: ${{ toJSON(secrets) }}
        secrets_env: all

    - name: Secrets to env testing
      uses: shine1594/secrets-to-env-action@v1.5.2
      with:
        secrets: ${{ toJSON(secrets) }}
        secrets_env: all
        file_name_prod: .env.testing
            
    - name: Run tests
      run: yarn test
