# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js

on: [push, pull_request]

jobs:
  run:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
      
    - name: Make envfile testing
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_APP_KEY: ${{ secrets.APP_KEY }}
        envkey_DB_DATABASE: ${{ secrets.DB_DATABASE }}
        envkey_DB_CONNECTION: mysql
        envkey_DB_HOST: ${{ secrets.DB_HOST }}
        envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        envkey_DB_USER: ${{ secrets.DB_USER }}
        envkey_MAIL_HOST: ${{ secrets.MAIL_HOST }}
        envkey_MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        envkey_MAIL_PORT: ${{ secrets.MAIL_PORT }}
        envkey_MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        envkey_SESSION_DRIVER: ${{ secrets.SESSION_DRIVER }}
        file_name: .env.testing
   
    - name: Make envfile prod
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_APP_KEY: ${{ secrets.APP_KEY }}
        envkey_DB_DATABASE: ${{ secrets.DB_DATABASE_PROD }}
        envkey_DB_CONNECTION: mysql
        envkey_DB_HOST: ${{ secrets.DB_HOST_PROD }}
        envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD_PROD }}
        envkey_DB_USER: ${{ secrets.DB_USER_PROD }}
        envkey_MAIL_HOST: ${{ secrets.MAIL_HOST }}
        envkey_MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        envkey_MAIL_PORT: ${{ secrets.MAIL_PORT }}
        envkey_MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        envkey_SESSION_DRIVER: ${{ secrets.SESSION_DRIVER }}
        file_name: .env
   
   
    - name: Run tests
      run: yarn test
