# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js

on: [push, pull_request]

jobs:
  run:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
      
    - name: Give permission createEnvFile
      run: chmod +x ./.github/createEnvFile.sh

    - name: Give permission createEnvTestingFle
      run: chmod +x ./.github/createEnvTestingFile.sh

    - name: Secrets to env
      run: ./.github/createEnvFile.sh "$secrets"
      env:
       secrets: ${{ toJson(secrets) }}
        
    - name: Secrets to env testing
      run: ./.github/createEnvTestingFile.sh "$secrets"
      env:
        secrets: ${{ toJson(secrets) }}
            
    - name: Run tests
      run: yarn test
